# Generated by Django 3.0.7 on 2021-12-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juicy_board', '0002_auto_20211206_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuicyBoard',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('pcode', models.CharField(db_column='PCODE', max_length=4)),
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=50, null=True)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=200, null=True)),
                ('content', models.CharField(blank=True, db_column='CONTENT', max_length=2000, null=True)),
                ('is_complete', models.IntegerField(blank=True, db_column='IS_COMPLETE', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='PRIORITY', null=True)),
                ('created_at', models.DateField(blank=True, db_column='CREATED_AT', null=True)),
            ],
            options={
                'db_table': 'juicy_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagCode',
            fields=[
                ('tcode', models.CharField(db_column='TCODE', max_length=4, primary_key=True, serialize=False)),
                ('tname', models.CharField(db_column='TNAME', max_length=200)),
            ],
            options={
                'db_table': 'TAG_CODE',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='juicy_board',
        ),
    ]
